### ISSUE TITLE
Zip binaries for Winget

### ISSUE THREAD

**Issue by sitiom** [JackMordaunt/icns#15]
Hi, this is a great project, and I plan to add this to [Winget](https://learn.microsoft.com/en-us/windows/package-manager/). However, Winget only supports installing from zip archives at the moment. Can you also please release alternative zip binaries in the releases? Thanks!

**Comment by JackMordaunt** [comment]
Done! Thanks :)

**Comment by sitiom** [comment]
Thanks, I've opened up a PR to add it to Winget:
- https://github.com/microsoft/winget-pkgs/pull/97893

Once the PR is merged, I can set up [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) in this repo.
