### ISSUE TITLE
gogio -  iconutil not present for Windows or Linux. Its a Mac native tool.

### ISSUE THREAD

**Issue by gedw99** [JackMordaunt/icns#20]
hey @JackMordaunt 

i guess this golang toll will replace the one using in gogio at:
https://github.com/gioui/gio-cmd/blob/0a86898b418418e80fba9c12e71dfdf764bb01d6/gogio/macosbuild.go#LL94C23-L94C31

**Comment by JackMordaunt** [comment]
Hi @gedw99 thanks for the report. I pushed a fix to the module name, so you should be able to run the command as specified in the readme!

**Comment by gedw99** [comment]
Thanks @JackMordaunt 

i am now integrating it into gogio.
At least trying it out.

We can either do it as an import OR as an exec on the binary.
I favour an import .
