### ISSUE TITLE
integration into gogio

### ISSUE THREAD

**Issue by gedw99** [JackMordaunt/icns#21]
Hey @andydotxyz 

am working on it here: https://github.com/gedw99/gio-sign/

gogio and icns looks like it can work together.  will make building cross platform.

The intent is that in CI, we can do a gio build and sign cross any platform to build any platform is the intent.

the rust signer can do this apparently. the signing from anywhere i mean.

first thing though is to get icns working with gogio and then get upstream.
we can integration the preview tool too after that if you want.

**Comment by andydotxyz** [comment]
I'm not sure what this issue is about - did you tag the wrong person perhaps?
I already use this great project in the Fyne packager, to get macOS packaging working without needing to be on Darwin.

**Comment by gedw99** [comment]
sorry @andydotxyz yep wrong person.

**Comment by gedw99** [comment]
@andydotxyz 
 [Geoffrey](https://fynelabs.com/geoffrey) looks good. yes would love to add gio support.

**Comment by JackMordaunt** [comment]
It should be very easy to integrate icns into your tool! Let me know if you need anything specific. 

> we can integration the preview tool too after that if you want.

Not sure what you mean by this.

**Comment by gedw99** [comment]
ok sounds like your cool with that... will proceed.
fyi @whereswaldon

**Comment by gedw99** [comment]
> > Is the code open ?
> 
> Not the overall platform, no. However it spins up fyne-cross to do the actual builds and that is all open... could explore options to add it in there, or have a compatible Gio runner?

sounds good. first lets get packaging working before the docker stuff though
ex:
https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/templates/templates.go

My idea is to have this sort of code shared like you and Christ did for Text stuff ...
