### ISSUE TITLE
Dropbox icns file: no icons found

### ISSUE THREAD

**Issue by Gys** [JackMordaunt/icns#5]
Hi

I want to decode the icons of a few apps. Several work well, but some do not. Like the icon of Dropbox which is stored at `/Applications/Dropbox.app/Contents/Resources/AppIcon.icns`. The files exists and opens in `Preview` without problems, showing the Dropbox icon in several sizes. However, this library reports the error `no icons found`?

**Comment by Gys** [comment]
[AppIcon.icns.zip](https://github.com/JackMordaunt/icns/files/6516812/AppIcon.icns.zip)

**Comment by JackMordaunt** [comment]
Hi @Gys, can you try rebuild from source and verify the problem persists. 

`git clone https://github.com/jackmordaunt/icns && cd icns && go install ./...`

**Comment by Gys** [comment]
The preview app works if I clone the project.

I realise now that by default the latest version (v2.*.*) is never installed! I always get the latest v1, which is old, but that is the one that I used previously... 

So there is a problem with the version tagging?

When I download the latest version:
go get github.com/jackmordaunt/icns@latest
I get:
go get: upgraded github.com/jackmordaunt/icns v0.0.0-20181231085925-4f16af745526 => v1.0.0

**Comment by JackMordaunt** [comment]
Yes I think this is an issue with go modules. 
I have created a `v2` branch and added a `/v2` suffix to the module path. 

Trying using the following commands to install:

`go install github.com/jackmordaunt/icns/v2/cmd/preview@latest`
`go install github.com/jackmordaunt/icns/v2/cmd/icnsify@latest`

**Comment by Gys** [comment]
Yes, now it a works as expected, thanks!
