### ISSUE TITLE
Moving the ui to a different repo?

### ISSUE THREAD

**Issue by Jacalz** [JackMordaunt/icns#8]
Hi. Thanks for creating this library. It is very useful for the packaging that we do in https://github.com/fyne-io/fyne.

The recent versions seem to have a ui and depend on gioui for it. This unfortunately means that anyone importing this will get gioui and its dependencies added to their go.sum as well. Given that we are a user interface too, this is something that we would like to avoid. Is moving the ui something that you could consider?

**Comment by JackMordaunt** [comment]
Yes absolutely.

The gioui package should have its own go.mod file. 

Again, sorry for seeing this so late.

**Comment by JackMordaunt** [comment]
I've given `cmd/preview` it's own `go.mod` to decouple the dependencies. In theory, if you only import Let me know if that works for you! Thanks.

**Comment by Jacalz** [comment]
That works flawlessly. Thank you very much. I will make sure to get Fyne updated to the latest release :)
